# File: .github/workflows/test-runner.yml
# MỤC ĐÍCH: Kiểm tra xem GitHub Actions có được bật trên repo này không.

name: Simple Push Tester

on:
  push:
    branches:
      - '**' # Chạy trên bất kỳ push nào tới bất kỳ nhánh nào

jobs:
  test:
    name: Print a message
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "✅ GitHub Actions are running correctly on this repository!"
